### ISSUE TITLE
Demo app from Google Play crashes - the one from repo works fine

### ISSUE THREAD

**Issue by snowpong** [flurgle/CameraKit-Android#18]
Your app on https://play.google.com/store/apps/details?id=com.flurgle.camerakit.demo crashes on my Huawei Mate 9 Pro (API-24). It crashes right after both the camera and audio permission requests and then fail to open again if I relaunch it.

The demo app from this repo works fine though.

**Comment by dwillmc** [comment]
An update was just pushed which should rollout in the next few hours and fix this problem.
Please re-open if you get the update and it still doesn't work!
