### ISSUE TITLE
wrong file name: AutoUnFocusEditText

### ISSUE THREAD

**Issue by muetzenflo** [flurgle/CameraKit-Android#3]
I just cloned the repo to find out why #2 is happening. In the current state you cannot compile, because the class AutoUnFocusEditText is not named correctly.

class name: AutoUnFocusEditText
file name: AutoUnfocusEditText

**Comment by dwillmc** [comment]
Good catch, it was originally `AutoUnfocusEditText` and later renamed to `AutoUnFocusEditText`, which git wouldn't have caught on MacOS. I've changed it and now filename matches class name.

c8e7f2924aec986ecd3232f07a9901f9d545baf5
